/**
 * Detecção de bots por User-Agent.
 * Não bloqueia — apenas marca o registro para filtragem no dashboard.
 */

const BOT_PATTERNS = [
  /bot/i,
  /crawl/i,
  /spider/i,
  /slurp/i,
  /googlebot/i,
  /Google-InspectionTool/i,
  /Google-Read-Aloud/i,
  /Google-Safety/i,
  /Google-Extended/i,
  /Google-Site-Verification/i,
  /Googlebot-Image/i,
  /Googlebot-Video/i,
  /Mediapartners-Google/i,
  /AdsBot-Google/i,
  /APIs-Google/i,
  /FeedFetcher-Google/i,
  /bingbot/i,
  /bingpreview/i,
  /yandex/i,
  /baidu/i,
  /duckduckbot/i,
  /facebookexternalhit/i,
  /facebookcatalog/i,
  /twitterbot/i,
  /linkedinbot/i,
  /whatsapp/i,
  /telegrambot/i,
  /discordbot/i,
  /slackbot/i,
  /viber/i,
  /applebot/i,
  /semrushbot/i,
  /ahrefsbot/i,
  /mj12bot/i,
  /dotbot/i,
  /rogerbot/i,
  /exabot/i,
  /python-requests/i,
  /go-http-client/i,
  /curl/i,
  /wget/i,
  /axios/i,
  /node-fetch/i,
  /httpx/i,
  /java\//i,
  /libwww/i,
  /scrapy/i,
  /HeadlessChrome/i,
  /PhantomJS/i,
  /Puppeteer/i,
  /Playwright/i,
  /PetalBot/i,
  /SeznamBot/i,
  /Qwantify/i,
  /archive\.org_bot/i,
  /CCBot/i,
  /GPTBot/i,
  /ChatGPT-User/i,
  /anthropic-ai/i,
  /ClaudeBot/i,
  /Google-Safety/i,
  /Vercelbot/i,
  /prerender/i,
  /Lighthouse/i,
  /PTST/i, // PageSpeed Insights
  /Chrome-Lighthouse/i,
  /Speed Insights/i,
  /GTmetrix/i,
  /pingdom/i,
  /UptimeRobot/i,
  /StatusCake/i,
]

export function isBot(userAgent: string | null): boolean {
  if (!userAgent || userAgent.trim() === '') return true
  return BOT_PATTERNS.some((pattern) => pattern.test(userAgent))
}
